export const ActionTypes = {
    SET_ASTRO_VIEW_MODE : "SET_ASTRO_VIEW_MODE",
    SET_SELECTED_ASTRO:"SET_SELECTED_ASTRO",
    ADD_AUTHTOKEN: "ADD_AUTHTOKEN",
    REMOVE_AUTHTOKEN:"REMOVE_AUTHTOKEN",
    EDIT_MODE:"EDIT_MODE"
}