

export const statusList = [
    { name: "Pending", code: "pending" },
    { name: "Approved", code: "approved" },
    { name: "Rejected", code: "rejected" }
];

export const productCatagory = [
    { name: "Rudraksha", code: "rudraksha" },
    { name: "Beads Bracelet", code: "beads_bracelet" },
    { name: "Gemstone", code: "gemstone" },
    { name: "Tulsi Mala", code: "tulsi_mala" },
    { name: "Healing Crystal", code: "healing_crystal" },
    { name: "Evil Eye", code: "evil_eye" },
    { name: "Pendants", code: "pendants" },
    { name: "Tumbles", code: "tumbles" },
];

export const qualityType = [
    { name: "Economy", code: "economy" },
    { name: 'Average', code: 'average' },
    { name: 'Premium', code: 'premium' },
    { name: 'Ultra Premium', code: 'ultra_premium' },
];

export const materialList = [
    { name: "Silver", code: "Silver" },
    { name: "Panchdhatu", code: "Panchdhatu" },
    { name: "Ashtdhatu", code: "Ashtdhatu" },
    { name: "Copper", code: "Copper" },
    { name: "Bronze", code: "Bronze" },
];

export const experienceList = [
    { name: "0 Year", id: "0" },
    { name: "1 Year", id: "1" },
    { name: "2 Years", id: "2" },
    { name: "3 Years", id: "3" },
    { name: "4 Years", id: "4" },
    { name: "5 Years", id: "5" },
    { name: "6 Years", id: "6" },
    { name: "7 Years", id: "7" },
    { name: "8 Years", id: "8" },
    { name: "9 Years", id: "9" },
    { name: "10 Years", id: "10" },
    { name: "10+ Years", id: "10" },
];

export const skillList = [
    { name: 'Face Reading', code: 'face reading' },
    { name: 'Life Coach', code: 'life coach' },
    { name: 'Nadi', code: 'nadi' },
    { name: 'Numerology', code: 'numerology' },
    { name: 'Palmistry', code: 'palmistry' },
    { name: 'Prashana', code: 'prashana' },
    { name: 'Psychic', code: 'psychic' },
    { name: 'Tarot', code: 'tarot' },
    { name: 'Vastu', code: 'vastu' },
    { name: 'Vedic', code: 'vedic' },
    { name: 'Lal Kitab', code: 'lal kitab' },
    { name: 'Match Making', code: 'match making' },
    { name: 'Medical Astrology', code: 'medical astrology' },
    { name: 'Birth Time Rectification', code: 'birth time rectification' },
    { name: 'Kundali', code: 'kundali' },
    { name: 'Crystal Healing', code: 'crystal healing' },
    { name: 'KP Astrology', code: 'kp astrology' },
    { name: 'Mantra', code: 'mantra' },
    { name: 'Meditation', code: 'meditation' },
    { name: 'Spiritual Healing', code: 'spiritual_healing' },
    { name: 'Fengshui', code: 'fengshui' },
    { name: 'Dream Interpretation', code: 'dream_interpretation' },
    { name: 'Theta Healing', code: 'theta_healing' },
    { name: 'Astrocartographer', code: 'astrocartographer' },
    { name: 'Celtic', code: 'celtic' },
    { name: 'Kabbalistic', code: 'kabbalistic' },
    { name: 'Financial', code: 'financial' },
    { name: 'Horary', code: 'horary' },
    { name: 'Synastry', code: 'synastry' },
    { name: 'Natal', code: 'natal' },
    { name: 'Western', code: 'western' },
];

export const specializationList = [
    { name: 'Compatibility Issues', code: 'compatibility issues' },
    { name: 'Career Struggles', code: 'career struggles' },
    { name: 'Health Concerns', code: 'health concerns' },
    { name: 'Financial Challenges', code: 'financial challenges' },
    { name: 'Personal Growth Issues', code: 'personal growth issues' },
    { name: 'Communication Difficulties', code: 'communication difficulties' },
    { name: 'Emotional Struggles', code: 'emotional struggles' },
    { name: 'Social Challenges', code: 'social challenges' },
    { name: 'Creative Blocks', code: 'creative blocks' },
    { name: 'Spiritual Conflicts', code: 'spiritual conflicts' },
    { name: 'Relationship Issues', code: 'relationship issues' },
    { name: 'Family Conflicts', code: 'family conflicts' },
    { name: 'Physical Health Concerns', code: 'physical health concerns' },
    { name: 'Addiction or Substance Abuse', code: 'addiction or substance abuse' },
    { name: 'Career Stagnation', code: 'career stagnation' },
    { name: 'Love Issues', code: 'love issues' },
    { name: 'Marriage Issues', code: 'marriage issues' },
    { name: 'Anxiety', code: 'anxiety' },
    { name: 'Depression', code: 'depression' },
    { name: 'Job Instability', code: 'job instability' },
    { name: 'Loneliness', code: 'loneliness' },
    { name: 'Social Isolation', code: 'social isolation' },
];

export const productSubCatagory = [
    { name: 'Agate', code: 'agate' },
    { name: 'Amethyst', code: 'amethyst' },
    { name: 'Blue Sapphire Bangkok', code: 'blue sapphire_bangkok' },
    { name: 'Blue Sapphire Ceylon', code: 'blue sapphire_ceylon' },
    { name: 'Cats Eye', code: 'cats_eye' },
    { name: 'Citrine', code: 'citrine' },
    { name: 'Coral Capsule', code: 'coral_capsule' },
    { name: 'American Diamond Ad', code: 'american_diamond_ad' },
    { name: 'Diamond', code: 'diamond' },
    { name: 'Emerald', code: 'emerald' },
    { name: 'Gomed Ceylon', code: 'gomed_ceylon' },
    { name: 'Iolite', code: 'iolite' },
    { name: 'Lapis Lazuli', code: 'lapis_lazuli' },
    { name: 'Malachite', code: 'malachite' },
    { name: 'Moissanite', code: 'moissanite' },
    { name: 'Onyx', code: 'onyx' },
    { name: 'Both Side Fire Opal', code: 'both_side_fire_opal' },
    { name: 'Pearl Japan Sea', code: 'pearl_japan_sea' },
    { name: 'Pearl South Sea', code: 'pearl_south_sea' },
    { name: 'Plan Opal', code: 'plan_opal' },
    { name: 'Ruby', code: 'ruby' },
    { name: 'Sphatik', code: 'sphatik' },
    { name: 'Tiger Eye', code: 'tiger_eye' },
    { name: 'Tourmaline', code: 'tourmaline' },
    { name: 'Turquoise American', code: 'turquoise_american' },
    { name: 'Turquoise Irani', code: 'turquoise_irani' },
    { name: 'White Coral Capsule', code: 'white_coral_capsule' },
    { name: 'Yellow Sapphire Bangkok', code: 'yellow_sapphire_bangkok' },
    { name: 'Yellow Sapphire Ceylon', code: 'yellow_sapphire_ceylon' },
    { name: 'Blue Topaz', code: 'blue_topaz' },
    { name: 'Coral Triangular', code: 'coral_triangular' },
    { name: 'Single Side Fire Opal', code: 'single_side_fire_opal' },
    { name: 'White Coral Trinaglur', code: 'white_coral_trinaglur' },
];